ANDROID: ASoC: Fix 'allmodconfig' build break
Export 'arch_setup_dma_ops' to fix the dependency added
if CONFIG_SND_SOC=m:

  ERROR: "arch_setup_dma_ops" [sound/soc/snd-soc-core.ko] undefined!

This should be followed up with a refactor that removes the dependency
(tracked in the cited bug).

Bug: 144369166
Fixes: cf1e35db7268 ("ANDROID: ASoC: core - add hostless DAI support")
Change-Id: Icf2daf1d92597e6dc9e723799ed7cea73e961227
Signed-off-by: Todd Kjos <tkjos@google.com>
(changed Fixes: tag to match android-5.4 commit)
Signed-off-by: Quentin Perret <qperret@google.com>