Revert "net: dccp: initialize (addr,port) listening hashtable"
This reverts commit f21d5005daae8fe2d35b599106a31f4396ac9c72.

Cause build failures when DCCP is modular.

ERROR: "inet_hashinfo2_init" [net/dccp/dccp.ko] undefined!

Signed-off-by: David S. Miller <davem@davemloft.net>